### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by mdeboer** [luizfilipe2557/owlcarousel-sync-plugin#1]
It would be nice to have it available through bower! 👍

**Comment by luizfilipe2557** [comment]
I don't know how to use or implement Bower, if anyone could help me I would really appreciate it!

**Comment by mdeboer** [comment]
It's really simple, mainly just creating the `bower.json` file by running `bower init`. You can find all about it here: [http://bower.io/docs/creating-packages/](http://bower.io/docs/creating-package)

**Comment by luizfilipe2557** [comment]
Could you test it? `$ bower info owl.carousel.sync`

**Comment by mdeboer** [comment]
Will do!

**Comment by mdeboer** [comment]
Sorry for my late comment, rather busy. It works perfectly!
